export enum TokenType {
    Unknown = "Unknown",
    BacktickToken = "BacktickToken",
    DollarBraceToken = "DollarBraceToken",
    CloseBraceToken = "CloseBraceToken",
    OpenParenthesisToken = "OpenParenthesisToken",
    CloseParenthesisToken = "CloseParenthesis",
    CommaToken = "CommaToken",
    IfKeyword = "IfKeyword",
    GetKeyword = "GetKeyword",
    LengthKeyword = "LengthKeyword",
    Whitespace = "Whitespace",
    Identifier = "Identifier",
    StringLiteral = "StringLiteral",
    NumericLiteral = "NumericLiteral",
    EqualityOperator = "EqualityOperator",
    GreaterThanToken = "GreaterThanToken",
    GreaterThanEqualsToken = "GreaterThanEqualsToken",
    LessThanToken = "LessThanToken",
    LessThanEqualsToken = "LessThanEqualsToken",
    BarBarToken = "BarBarToken",
    TrueKeyword = "TrueKeyword",
    FalseKeyword = "FalseKeyword",
    EndOfFileToken = "EndOfFileToken",
    UndefinedKeyword = "UndefinedKeyword"
}